// Database types for Supabase
// These will be generated by Supabase CLI once the database is set up

export type UserType = 'customer' | 'staff' | 'business_owner' | 'admin'
export type BusinessStatus = 'pending' | 'approved' | 'suspended'
export type SubscriptionStatus = 'active' | 'cancelled' | 'past_due'
export type SubscriptionPeriod = 'day' | 'week' | 'month'
export type StampRequestStatus = 'pending' | 'approved' | 'rejected'
export type ReferralStatus = 'pending' | 'qualified' | 'credited' | 'expired'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          name: string
          phone: string | null
          profile_picture_url: string | null
          user_type: UserType
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string // Required - must match auth.users id
          email: string
          name: string
          phone?: string | null
          profile_picture_url?: string | null
          user_type: UserType
          created_at?: string
          updated_at?: string
        }
        Update: {
          email?: string
          name?: string
          phone?: string | null
          profile_picture_url?: string | null
          user_type?: UserType
          updated_at?: string
        }
      }
      businesses: {
        Row: {
          id: string
          owner_id: string
          name: string
          type: string
          address: string
          lat: number
          lng: number
          email: string
          phone: string
          logo_url: string | null
          cover_photos: string[]
          description: string | null
          website: string | null
          social_links: Record<string, string> | null
          opening_hours: Record<string, { open: string; close: string }> | null
          google_place_id: string | null
          google_rating: number | null
          status: BusinessStatus
          stripe_account_id: string | null
          commission_rate: number
          branding: {
            background_color?: string
            text_color?: string
            accent_color?: string
          } | null
          created_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          name: string
          type: string
          address: string
          lat: number
          lng: number
          email: string
          phone: string
          logo_url?: string | null
          cover_photos?: string[]
          description?: string | null
          website?: string | null
          social_links?: Record<string, string> | null
          opening_hours?: Record<string, { open: string; close: string }> | null
          google_place_id?: string | null
          google_rating?: number | null
          status?: BusinessStatus
          stripe_account_id?: string | null
          commission_rate?: number
          branding?: {
            background_color?: string
            text_color?: string
            accent_color?: string
          } | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['businesses']['Insert']>
      }
      business_staff: {
        Row: {
          id: string
          business_id: string
          user_id: string
          role: 'staff' | 'owner'
          invited_at: string
          accepted_at: string | null
        }
        Insert: {
          id?: string
          business_id: string
          user_id: string
          role: 'staff' | 'owner'
          invited_at?: string
          accepted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['business_staff']['Insert']>
      }
      subscription_products: {
        Row: {
          id: string
          business_id: string
          name: string
          description: string | null
          items: { type: string; quantity: number }[]
          quantity_per_period: number
          period: SubscriptionPeriod
          price_gbp: number
          blackout_times: { day: number; start: string; end: string }[]
          branding: {
            background_color?: string
            text_color?: string
            accent_color?: string
          } | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          description?: string | null
          items: { type: string; quantity: number }[]
          quantity_per_period: number
          period: SubscriptionPeriod
          price_gbp: number
          blackout_times?: { day: number; start: string; end: string }[]
          branding?: {
            background_color?: string
            text_color?: string
            accent_color?: string
          } | null
          is_active?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['subscription_products']['Insert']>
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          product_id: string
          stripe_subscription_id: string
          status: SubscriptionStatus
          current_period_start: string
          current_period_end: string
          cancelled_at: string | null
          cancel_reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          product_id: string
          stripe_subscription_id: string
          status?: SubscriptionStatus
          current_period_start: string
          current_period_end: string
          cancelled_at?: string | null
          cancel_reason?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['subscriptions']['Insert']>
      }
      redemptions: {
        Row: {
          id: string
          subscription_id: string
          item_type: string
          redeemed_at: string
          undone_at: string | null
          undone_by: string | null
        }
        Insert: {
          id?: string
          subscription_id: string
          item_type: string
          redeemed_at?: string
          undone_at?: string | null
          undone_by?: string | null
        }
        Update: Partial<Database['public']['Tables']['redemptions']['Insert']>
      }
      loyalty_cards: {
        Row: {
          id: string
          business_id: string
          name: string
          stamps_required: number
          reward: string
          item_stamped: string
          expiry_days: number | null
          bonus_days: { day: number; multiplier: number }[]
          branding: {
            background_color?: string
            text_color?: string
            accent_color?: string
          } | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          stamps_required: number
          reward: string
          item_stamped: string
          expiry_days?: number | null
          bonus_days?: { day: number; multiplier: number }[]
          branding?: {
            background_color?: string
            text_color?: string
            accent_color?: string
          } | null
          is_active?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['loyalty_cards']['Insert']>
      }
      loyalty_memberships: {
        Row: {
          id: string
          user_id: string
          card_id: string
          current_stamps: number
          last_stamp_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          card_id: string
          current_stamps?: number
          last_stamp_at?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['loyalty_memberships']['Insert']>
      }
      stamps: {
        Row: {
          id: string
          membership_id: string
          awarded_by: string | null
          awarded_at: string
          is_request: boolean
          request_status: StampRequestStatus | null
          approved_by: string | null
          approved_at: string | null
        }
        Insert: {
          id?: string
          membership_id: string
          awarded_by?: string | null
          awarded_at?: string
          is_request?: boolean
          request_status?: StampRequestStatus | null
          approved_by?: string | null
          approved_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['stamps']['Insert']>
      }
      referrals: {
        Row: {
          id: string
          referrer_id: string
          referred_id: string
          business_id: string
          referral_code: string
          status: ReferralStatus
          qualified_at: string | null
          credited_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          referrer_id: string
          referred_id: string
          business_id: string
          referral_code: string
          status?: ReferralStatus
          qualified_at?: string | null
          credited_at?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['referrals']['Insert']>
      }
      credits: {
        Row: {
          id: string
          user_id: string
          business_id: string
          amount_gbp: number
          source: 'referral' | 'promo'
          referral_id: string | null
          expires_at: string
          used_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          business_id: string
          amount_gbp: number
          source: 'referral' | 'promo'
          referral_id?: string | null
          expires_at: string
          used_at?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['credits']['Insert']>
      }
    }
  }
}
